### ISSUE TITLE
Accordion: Missing CSS Styles

### ISSUE THREAD

**Issue by shazahm1** [kadencewp/kadence-blocks#98]
While in the Editor the icon has a padding applied which looks nice:

``` css
.kt-btn-svg-icon.kt-btn-side-left {
	padding-right: 5px;
}
```

However, on the published page/post, the style does not exist so the icon and text run together.
